### PR TITLE
AOT executables by @AsynchronousAI and internal package searching

### PR DESCRIPTION
**Pull request by Frityet**
new PR based off #12

### CODE REVIEW

**Comment by Frityet** [comment]
@hugomg This should be ready for review

**Comment by hugomg** [comment]
Can you help me understand why we still need the internal searchers? Why is the default searcher not sufficient?

**Comment by Frityet** [comment]
> Can you help me understand why we still need the internal searchers? Why is the default searcher not sufficient?

I said misinformation within that chain, I had believed that the default searcher searched within the binary. This is false, and I discovered the reason why the lua `require` error had the info about searching inside the executable is because I had propogated that information within my searcher with `dlerror`. Lua itself does not search within the executable

**Comment by hugomg** [comment]
Alright, I think I understand this a bit better now that I have looked into how other tools do this. Yes, Lua's default require doesn't look inside the current executable. The only way to do this is to add a new searcher to `package.searchers`, at the top of the searcher list.

However, if we are working with statically-linked executables then we should not need to fiddle with `dlopen` or platform-specific code. In luastatic, the `main` initializes a module table with all the `luaopen` functions. This table then gets passed to the actual searcher function, which is implemented [in Lua](https://github.com/ers35/luastatic/blob/c3e1b2ef8f998230fb4c47935e4bdcb1610abab5/luastatic.lua#L329).

```c
lua_newtable(L);

int luaopen_bar(lua_State *L);
lua_pushcfunction(L, luaopen_foo);
lua_setfield(L, -2, "foo");

int luaopen_bar(lua_State *L);
lua_pushcfunction(L, luaopen_bar);
lua_setfield(L, -2, "bar");
```

Naturally, this requires knowing ahead of time the name of all the luaopen functions that will be used. They would need to be passed as command-line arguments, probably.

I'm starting to think that we probably would be better off avoiding this altogether and encouraging people to use `luastatic` instead. The only major "downside" I see is that luastatic, as well as most of those other tools, assume that your main.lua entry point is written in non-compiled Lua. We would need to instruct people to create a main.lua one-liner that merely calls into the compiled Lua.

**Comment by Frityet** [comment]
> However, if we are working with statically-linked executables then we should not need to fiddle with dlopen or platform-specific code. In luastatic, the main initializes a module table with all the luaopen functions. This table then gets passed to the actual searcher function, which is implemented [in Lua](https://github.com/ers35/luastatic/blob/c3e1b2ef8f998230fb4c47935e4bdcb1610abab5/luastatic.lua#L329).

That is a good solution, but one of the reasons why I specifically did it this way aswell is for if you link in a statically linked lua library, for example, I built `lfs.a`, and statically linked it in, and with the solution described I would need to specify somewhere in the .c file that `luaopen_lfs` is defined, which as you said could just be passed in as command line arguments.

> I'm starting to think that we probably would be better off avoiding this altogether and encouraging people to use luastatic instead. The only major "downside" I see is that luastatic, as well as most of those other tools, assume that your main.lua entry point is written in non-compiled Lua. We would need to instruct people to create a main.lua one-liner that merely calls into the compiled Lua.

I would much much less prefer this, as not only would this require installing and using another tool for building, but also make the whole process more complicated with what you said, making a stub to call into the compiled lua

**Comment by hugomg** [comment]
> and with the solution described I would need to specify somewhere in the .c file that luaopen_lfs is defined

This is an area that the various packing tools have different solutions. Luastatic uses "nm" to inspect the ".a" files. Luapak expects a Luarocks rockspec. Some tools run the original code one time and record everything that got require-d.

> as not only would this require installing and using another tool for building

I don't think that's all that bad though. They also have features that we don't have.

> but also make the whole process more complicated with what you said, making a stub to call into the compiled lua

But on the other hand we would be adding our own complexities to the code base... I doubt we would get all the corner cases right in the first try.

The red line that I would rather not cross is platform-specific code. I've been bit in the past by things not working on macos, or some system configuration I didn't think of.

**Comment by Frityet** [comment]
> This is an area that the various packing tools have different solutions. Luastatic uses "nm" to inspect the ".a" files. Luapak expects a Luarocks rockspec. Some tools run the original code one time and record everything that got require-d.

Which is why I think that using this method could be beneficial, as compared to those other methods, this is the most simplest, relying on a function and call already implemented within lua itself.

> I don't think that's all that bad though. They also have features that we don't have.

But having to install and use the tool for features you might not use, as at the code of this loader, it is just to make it easy to include multiple Lua files in one executable, which is a pretty core part of a lua project.

> But on the other hand we would be adding our own complexities to the code base... I doubt we would get all the corner cases right in the first try.

This is a good point, with proper testing I feel like it could be mitigated though

> The red line that I would rather not cross is platform-specific code. I've been bit in the past by things not working on macos, or some system configuration I didn't think of.

I do agree with this, and this is a risk that is taken, but I do believe because it is optional relying on the `-i` flag that it partially mitigates this, as the program would still work in the other ways mentioned, just with more difficult and tedious building.

The functions i specifically chose within the PR are just the functions which are already present within the Lua codebase. Another reason why I don't think "just use luastatic" is a good option is because it is also system specific too, where you can't use it on windows without a posix emulation terminal

**Comment by Frityet** [comment]
@hugomg Whats the status of getting this merged, should I remove the internal package loader?

**Comment by hugomg** [comment]
I think we can merge if we remove the package loader. It won't be perfect (for perfect, I suppose using an external tool would be better) but it should be sufficient for simpler programs without complicated dependencies, without interpreted Lua modules, etc.

**Comment by Frityet** [comment]
> I think we can merge if we remove the package loader. It won't be perfect (for perfect, I suppose using an external tool would be better) but it should be sufficient for simpler programs without complicated dependencies, without interpreted Lua modules, etc.

Will do 👍

**Comment by Frityet** [comment]
removed

**Comment by Frityet** [comment]
uh my PR is busted ill make a new one

**Pull request closed without merging**
